services:
  nginx:
    restart: always
    image: nginx

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.test.entrypoints=https"
      - "traefik.http.routers.test.rule=Host(`$TEST_SERVER_DOMAIN`)"
      - "traefik.http.routers.test.tls.certresolver=letsEncrypt"
      - "traefik.docker.network=proxy"

    networks:
      - proxy

networks:
  proxy:
    external: True
